--
-- PostgreSQL database dump
--

\restrict oLOqDPgbNjX5HSVXeGr19QgD1JaPsPQIRMslhhXVvIoMz1LxiZkIezTucDvg31U

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-06-25 09:20:10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 32769)
-- Name: tickets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tickets (
    fecha_creacion timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    descripcion text,
    estado character varying(255) NOT NULL,
    prioridad character varying(255) NOT NULL,
    titulo character varying(255) NOT NULL
);


ALTER TABLE public.tickets OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 32768)
-- Name: tickets_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tickets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tickets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 32783)
-- Name: usuarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios (
    fecha_creacion timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    apellido character varying(255),
    email character varying(255) NOT NULL,
    nombre character varying(255),
    password character varying(255) NOT NULL
);


ALTER TABLE public.usuarios OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 32782)
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4970 (class 0 OID 32769)
-- Dependencies: 220
-- Data for Name: tickets; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tickets (fecha_creacion, id, usuario_id, descripcion, estado, prioridad, titulo) FROM stdin;
2026-06-25 08:26:42.066228	1	1	3	Abierto	Baja	a
\.


--
-- TOC entry 4972 (class 0 OID 32783)
-- Dependencies: 222
-- Data for Name: usuarios; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuarios (fecha_creacion, id, apellido, email, nombre, password) FROM stdin;
2026-06-25 08:26:33.750558	1	bc	bogadosantino137@gmail.com	a	13371444
\.


--
-- TOC entry 4978 (class 0 OID 0)
-- Dependencies: 219
-- Name: tickets_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tickets_id_seq', 1, true);


--
-- TOC entry 4979 (class 0 OID 0)
-- Dependencies: 221
-- Name: usuarios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuarios_id_seq', 1, true);


--
-- TOC entry 4816 (class 2606 OID 32781)
-- Name: tickets tickets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_pkey PRIMARY KEY (id);


--
-- TOC entry 4818 (class 2606 OID 32795)
-- Name: usuarios usuarios_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_email_key UNIQUE (email);


--
-- TOC entry 4820 (class 2606 OID 32793)
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- TOC entry 4821 (class 2606 OID 32796)
-- Name: tickets fkblaq7syvrsnelr3armtq2r9rm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT fkblaq7syvrsnelr3armtq2r9rm FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);


-- Completed on 2026-06-25 09:20:11

--
-- PostgreSQL database dump complete
--

\unrestrict oLOqDPgbNjX5HSVXeGr19QgD1JaPsPQIRMslhhXVvIoMz1LxiZkIezTucDvg31U

