# Conexión con la Base de Datos que acabas de crear en pgAdmin
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_tickets
spring.datasource.username=postgres
spring.datasource.password=13371444
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate para auto-crear las tablas de tus entidades Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
